### PR TITLE
stivale2.1: yes

### PR DESCRIPTION
**Pull request by Andy-Python-Programmer**
Signed-off-by: Andy-Python-Programmer <andypythonappdeveloper@gmail.com>

### CODE REVIEW

**Comment by pitust** [comment]
stivale2.1 sounds like the name of the diesese+crab bad

**Comment by Andy-Python-Programmer** [comment]
then what should I name it?

**Comment by leap0x7b** [comment]
> stivale2.1 sounds like the name of the diesese+crab bad

ratio + you fell off + l + rust good + shill aero

**Comment by Neptune650** [comment]
Do you realize this pull request will be most likely denied?, Plus there are multiple typos.

**Comment by Andy-Python-Programmer** [comment]
This is one of the shortcomings of stivale 2 and there is no reason for this pull to be rejected. The patch is reasonable and is not a breaking change.

I don't program in Microsoft Word so there will be typos.

**Comment by Mintsuki** [comment]
They are not VLAs.

**Comment by ilobilo** [comment]
But sometimes vscode intellisense stops working because they do not have size dpecified

**Comment by Mintsuki** [comment]
Sounds like a vscode issue? Open a bug with them

**Comment by Andy-Python-Programmer** [comment]
Closing the pull request since as discussed this feature will be merged into stivale 3. The next gen boot protocol.

**Comment by ominitay** [comment]
lol what? this is a joke, right?

**Pull request closed without merging**
